version: '3.6'

services:
  proxy-node:
    image: rodamianro/util:proxy-node
    container_name: proxy-node
    env_file:
      - .env
    networks:
      proxy-network:
    ports:
      - ${DOCKER_PORT}:${PORT}

networks:
 proxy-network:
    driver: bridge
